### ISSUE TITLE
Episode I Discussion issue.

### ISSUE THREAD

**Issue by Bertram25** [ValyriaTear/ValyriaTear#126]
A place to talk in github for the next part of the episode I. :)

**Episode I Release TODO List:**
- [x] Do not forget to add the dead ally target type for resurrect-based spells.
- [x] Add support for scripted animations in battle animation scripts (other than on the battle actor but also on them). #222
- [x] Add "soft-edge" character movement support #208 
- [x] Use Lilou's new horse
- [x] Add missing shoulders to existing portraits if possible
- [x] Fix menu list refresh in certain cases #248
- [x] Finish the Joystick D-Pad support #257 
- [x] Add Episode ending complete credits. #268 
- [x] Fix broken parallax effects in the Mt. Elbrus exterior and the Layna Forest caves map scripts.
- [x] Spread back status effects to the map mode. I could also add traps in the dungeon poisoning the characters, for instance. #220 
- [x] Fix first item being listed twice in the trade mode. #283 
- [x] Add support to change the welcome text in the shop mode through a ShopEvent. #284
- [x] Add support to disable the ability to sell in the shop mode. #285 
- [x] Fix item list handling with one item in battles. #282 
- [x] Decrease the characters agility at battle start when they are low on Stamina on map. #289
- [x] Remove the art/ folder from this repo, and put art/ in its own. #287
- [x] Improve a bit the stun particle effect.
- [x] Fix Skeletons offset due to Bronann's attack looking weird on them.
- [x] Make the Battle item/skill info window speak about seconds, not milliseconds.
- [x] Add support to show canceled quests (like when you didn't finish the chicken quest on time.) #288 
- [x] Fix enemy behaviour #307 
- [x] Fix last cppcheck warnings #306 
- [x] Add memory support for shops #298 (Main part done, the next one after release.)
- [x] Check Credits completeness
- [x] Translation & migration to transifex.
- [x] Fix Kalya's skill 'Rain of Arrows' #325
- [x] Add second dungeon and boss. #286 
- [x] Do no forget to add ending credits music. (Used the sad theme)
- [x] Episode I RC1 Release! :D
- [x] Kill all the issues found.
- [x] Episode I Release! :D
