### ISSUE TITLE
[Tracker] Issues with item menu and submenus in the MenuMode

### ISSUE THREAD

**Issue by akien-mga** [ValyriaTear/ValyriaTear#359]
I noticed several issues with the item menu and its submenus. I'll describe them all in this tracker bug since I think most of several are related with one another.
- [x] Submenu descriptions are wrong and change after one key press
- [x] Non-usable items can be selected and are rearranged
- [x] Most items in submenus get thrown to the end of the list if selected and then a key is pressed
- [x] "Potion" submenu icon is not as good as the other ones
##### Submenu descriptions are wrong and change after one key press

When you open the Item menu, the description of the selected submenu is "Select an item to Equip or Use", and if you press any key, or change to any submenu, it becomes "Select a character to use the item on". The second description is wrong, and the first one could also be better since the meaning should be like "Browse through the <Name> menu, and select an item to use it." BTW, one can't equip an item through this menu, so that part is wrong too.

Note that when you open a submenu and go back with "Cancel", the description goes back to the first one ("Select an item to Equip or Use")
##### Non-usable items can be selected (in submenus)

Note that this doesn't concern the main item menu (" - "), where non-usable items can't be selected. In other submenus, if you select a non-usable item (e.g. "Iron ore") once, you hear the usual buzz meaning that it can't be selected, but if you try a second time, you can select it and then apply it to a character. (And I just lost a precious Iron ore doing so, you vicious developer! :-D).
##### Most items in submenus get thrown to the end of the list if selected and then a key is pressed

Closely related to the issue above, if you select an item in a submenu (not necessarily unusable, though it applies to those too), and then you press a key, the item goes to the bottom of the list of items.

This does not apply to: Minor Healing Potion, Healing Potion, Minor Elixir, Small Moon Juice Potion.
There might be others, but for example Elixir and Agility Potion are affected.

Probably because of this, the ordering the " - " tab and the "Potion" tab is not the same for similar objects.
##### "Potion" submenu icon is not as good as the other ones

As shown on the screenshot, the "potion" icon does not have the neat blue line that the other icons have at the interface with their alpha layer. It would be nice to improve the potion icon.

![valyriatear-enhancement-submenus](https://cloud.githubusercontent.com/assets/4701338/3869573/f9e40f82-2098-11e4-996f-c9664dec95c6.png)
